### ISSUE TITLE
Timeout loading page after 300000ms error

### ISSUE THREAD

**Issue by joebywan** [cwoac/thingy_grabber#12]
Managed to bust it again :D  Being that it's a timeout error I've tested it over a number of days to be sure it's happening on the same user, and it is.  User: jimjimjimmyjim

`Downloading thing 548 - 4124416
Traceback (most recent call last):
  File "D:\waste\thingygrabber\thingy_grabber.py", line 321, in _parse
    BROWSER.get(url)
  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\we
bdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\we
bdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\er
rorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Timeout loading page after
 300000ms

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\waste\thingygrabber\thingy_grabber.py", line 690, in <module>
    main()
  File "D:\waste\thingygrabber\thingy_grabber.py", line 676, in main
    Designs(user, args.directory, args.quick).download()
  File "D:\waste\thingygrabber\thingy_grabber.py", line 270, in download
    RC = Thing(thing).download(self.download_dir)
  File "D:\waste\thingygrabber\thingy_grabber.py", line 423, in download
    self._parse(base_dir)
  File "D:\waste\thingygrabber\thingy_grabber.py", line 330, in _parse
    logging.error(pc.log)
UnboundLocalError: local variable 'pc' referenced before assignment
`

Can not complete the user without this error occurring.

**Comment by cwoac** [comment]
OK. Weird. Is it always the same thing of that user?

**Comment by cwoac** [comment]
Hmmm. He has 1522 things. I can believe you are falling foul of rate limiting on the server side.

**Comment by joebywan** [comment]
I've downloaded things much faster than this in the past before, so it shouldn't be that.

**Comment by cwoac** [comment]
So, the latest version removes the use of a background browser app, so there is no longer an asynchronous wait to timeout, so this is fixed by way of code deletion :).
