### ISSUE TITLE
Code 502 Login Server exception

### ISSUE THREAD

**Issue by MohrMa2** [cwoac/thingy_grabber#25]
The program suddenly stopped working. I assume, thingiverse changed some details.
I created a different api.key but no change in the results.

The following errors are created:
PS C:\mohrma2\MM\3D_printer\_Tools>.\thingy_grabber.exe -a api.key collection spacemarcy lego
Got unexpected code 502 from url https://api.thingiverse.com/users/spacemarcy/collections/all?access_token=***.key: {"er
ror":"Login server exception"}
No URL set - object not initialised properly?
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\thingy_grabber\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, i
n run
  File "c:\programdata\anaconda3\envs\thingy_grabber\lib\site-packages\cx_Freeze\initscripts\Console.py", line 33, in ru
n
  File "thingy_grabber.py", line 895, in <module>
  File "thingy_grabber.py", line 876, in main
  File "thingy_grabber.py", line 288, in download
  File "thingy_grabber.py", line 262, in get
ValueError: No URL set - object not initialised properly?
Process Downloader-1:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\thingy_grabber\lib\multiprocessing\process.py", line 297, in _bootstrap
  File "thingy_grabber.py", line 213, in run
  File "c:\programdata\anaconda3\envs\thingy_grabber\lib\multiprocessing\queues.py", line 94, in get
  File "c:\programdata\anaconda3\envs\thingy_grabber\lib\multiprocessing\connection.py", line 216, in recv_bytes
  File "c:\programdata\anaconda3\envs\thingy_grabber\lib\multiprocessing\connection.py", line 306, in _recv_bytes
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\thingy_grabber\lib\multiprocessing\util.py", line 357, in _exit_function
  File "c:\programdata\anaconda3\envs\thingy_grabber\lib\multiprocessing\process.py", line 140, in join
  File "c:\programdata\anaconda3\envs\thingy_grabber\lib\multiprocessing\popen_spawn_win32.py", line 104, in wait
KeyboardInterrupt

**Comment by MohrMa2** [comment]
Sorry my fault. 
Thingiverse somehow deleted all my collections.
