### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by joebywan** [cwoac/thingy_grabber#5]
`Looking for old dir at ./stls/agentsmith99\GrotMeks-Trakta-Gun-Warehammer-40K
Copying 0 unchanged files.
Downloading 11 new files of 11
Downloading 13 images.
Downloading license
Downloading thing 9 - 3170298
[0, 22, 2018]
[0, 22, 2018]
[0, 22, 2018]
[0, 22, 2018]
[0, 22, 2018]
[0, 22, 2018]
[0, 22, 2018]
[0, 22, 2018]
[0, 22, 2018]
[0, 22, 2018]
[0, 22, 2018]
[0, 22, 2018]
[0, 22, 2018]
[0, 22, 2018]
[0, 22, 2018]
[0, 22, 2018]
[0, 22, 2018]
Looking for old dir at ./stls/agentsmith99\Grot-Hanomag-Warhammer-40K
Traceback (most recent call last):
  File "D:\waste\thingygrabber\thingy_grabber.py", line 660, in <module>
    main()
  File "D:\waste\thingygrabber\thingy_grabber.py", line 648, in main
    Designs(user, args.directory, args.quick).download()
  File "D:\waste\thingygrabber\thingy_grabber.py", line 241, in download
    RC = Thing(thing).download(self.download_dir)
  File "D:\waste\thingygrabber\thingy_grabber.py", line 433, in download
    new_last_time = new_file_links[0].last_update
IndexError: list index out of range`

This was done using thingy_grabber.py -d .\stls\ user agentsmith99

That's not the only user I'm getting it on.  Just incase you think it's an isolated case.  AntomanElven\Lucius-Pattern-head-for-Mars-Warlord-Titanicus-scale is another.  So far I've gotten it about 4 times today on different ones.

**Comment by cwoac** [comment]
interesting, so it thinks the model has been updated, but none of the files have newer timestamps. Possibly a readme change or something?

**Comment by joebywan** [comment]
In my list of 150 odd users to grab it's happening quite frequently.

**Comment by cwoac** [comment]
Turned out to be an actual bug rather than just another thingiverse edge case - parsing dates was broken for things where all the files were in October, after the 9th (would also have been wrong for some others, but wouldn't have failed).
 Fixed by 1267e583c51d66001bf9aeac090ddd37132ee027
