### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u0414' in position 102: character maps to <undefined>

### ISSUE THREAD

**Issue by joebywan** [cwoac/thingy_grabber#6]
Thanks for fixing that last one.  Did some more road testing and found this one.

Looking for old dir at .\stls\alphaflight83 designs\Wedding-Favor-Heart-Pendant
Traceback (most recent call last):
  File "D:\thingygrabber\thingy_grabber.py", line 661, in <module>
    main()
  File "D:\thingygrabber\thingy_grabber.py", line 649, in main
    Designs(user, args.directory, args.quick).download()
  File "D:\thingygrabber\thingy_grabber.py", line 241, in download
    RC = Thing(thing).download(self.download_dir)
  File "D:\thingygrabber\thingy_grabber.py", line 463, in download
    fl_handle.write("{},{},{}, {}\n".format(fl.link, fl.name, fl.last_update, ba
se_link))
  File "C:\Program Files\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0414' in position
102: character maps to <undefined>

**Comment by cwoac** [comment]
Hmmm. Looks like I need to sanitise filenames
